namespace: sample
pages:
    - pageID: 331565195186972661
      handle: pagetwohandle
      title: page two
      description: sample
      visible: true
      weight: 1
      createdAt: "2023-04-07T14:14:17+05:30"
      updatedAt: "2023-04-14T12:26:56+05:30"
