asdf
namespace: sample
modules:
    usershandle:
        moduleID: 330980806468083957
        name: users
        fields:
            name:
                kind: String
                label: name
                config:
                    dal:
                        encodingstrategy: null
                    privacy:
                        sensitivitylevelid: 0
                        usagedisclosure: ""
                    recordrevisions:
                        skip: false
        createdAt: "2023-04-03T13:28:54+05:30"
        updatedAt: "2023-04-03T13:32:41+05:30"
